/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class run extends javax.swing.JFrame {
    ImageIcon icon,icon1;
    private int random,atk,atk2,atk3,atk4,atk5,atk6;
    int healE = 390;
    int clicks;
    String input1,input2,input3,input4,input5,input6;
    pokemon pk;
    public run() {
        try{
        initComponents();
         setResizable(false);
         setLocationRelativeTo(null);  
         Poke1.setVisible(false);
         Poke2.setVisible(false);
         Poke3.setVisible(false);
         Poke4.setVisible(false);
         Poke5.setVisible(false);
         Poke6.setVisible(false);
         Skill1.setVisible(false);
         Skill2.setVisible(false);
         Skill3.setVisible(false);
         Skill4.setVisible(false);
         Lv.setText("LV.50");
         Name.setText("Charmeleon");        
         HP.setText(String.valueOf(healE));
         icon1 = new ImageIcon(getClass().getResource("Charmeleon.png"));
	 icon1.getImage().flush();
	 Epoke.setIcon(icon1);	
         atk = (int) (Math.random()*10+70);
         atk2 = (int) (Math.random()*10+70);
         atk3 = (int) (Math.random()*10+70);
         atk4 = (int) (Math.random()*10+70);
         atk5 = (int) (Math.random()*10+70);
         atk6 = (int) (Math.random()*10+70);
         pk = new pokemon();
        }catch(Exception e){}
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Run = new javax.swing.JButton();
        Fight = new javax.swing.JButton();
        Bag = new javax.swing.JButton();
        Pokemon = new javax.swing.JButton();
        Skill4 = new javax.swing.JButton();
        Skill1 = new javax.swing.JButton();
        Skill2 = new javax.swing.JButton();
        Skill3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Lv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        HP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Name1 = new javax.swing.JLabel();
        Lv1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HP1 = new javax.swing.JLabel();
        Epoke = new javax.swing.JLabel();
        poke = new javax.swing.JLabel();
        Poke1 = new javax.swing.JButton();
        Poke2 = new javax.swing.JButton();
        Poke3 = new javax.swing.JButton();
        Poke4 = new javax.swing.JButton();
        Poke5 = new javax.swing.JButton();
        Poke6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        getContentPane().add(Run, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, 50));

        Fight.setText("Fight");
        Fight.setActionCommand("Fight");
        Fight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FightActionPerformed(evt);
            }
        });
        getContentPane().add(Fight, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 120, 50));

        Bag.setText("BAG");
        getContentPane().add(Bag, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 120, 50));

        Pokemon.setText("Pokemon");
        Pokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PokemonActionPerformed(evt);
            }
        });
        getContentPane().add(Pokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 120, 50));

        Skill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill4ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 120, 30));

        Skill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill1ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 30));

        Skill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill2ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 120, 30));

        Skill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill3ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 120, 30));

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, -1, -1));
        jPanel1.add(Lv, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 17, -1, -1));

        jLabel1.setText("HP:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 76, -1, -1));

        HP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 76, 121, 42));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 120));

        jPanel2.setBackground(new java.awt.Color(204, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, -1, -1));
        jPanel2.add(Lv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 17, -1, -1));

        jLabel2.setText("HP:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 76, -1, -1));

        HP1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(HP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 76, 121, 42));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 270, 120));
        getContentPane().add(Epoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 300, 270));
        getContentPane().add(poke, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 240));

        Poke1.setText("Charmeleon");
        Poke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke1ActionPerformed(evt);
            }
        });
        getContentPane().add(Poke1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        Poke2.setText("Ivysaur");
        Poke2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke2ActionPerformed(evt);
            }
        });
        getContentPane().add(Poke2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        Poke3.setText("Butterfree");
        Poke3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke3ActionPerformed(evt);
            }
        });
        getContentPane().add(Poke3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        Poke4.setText("Ekans");
        Poke4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke4ActionPerformed(evt);
            }
        });
        getContentPane().add(Poke4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        Poke5.setText("Pidgeotto");
        Poke5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke5ActionPerformed(evt);
            }
        });
        getContentPane().add(Poke5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        Poke6.setText("Rattata");
        Poke6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poke6ActionPerformed(evt);
            }
        });
        getContentPane().add(Poke6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        System.exit(0);
    }//GEN-LAST:event_RunActionPerformed

    private void FightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FightActionPerformed
          Object source = evt.getSource();		
             if(source == Fight){
             if(clicks%2 == 0){
           	Skill1.setVisible(true);
           	Skill2.setVisible(true);
           	Skill3.setVisible(true);
           	Skill4.setVisible(true);               
             }
             if(clicks%2 == 1){
           	 Skill1.setVisible(false);
           	Skill2.setVisible(false);
           	Skill3.setVisible(false);
           	Skill4.setVisible(false);    
             }     
              clicks++;  
           }           
    }//GEN-LAST:event_FightActionPerformed

    private void Poke2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke2ActionPerformed
        Ivysaur();
    }//GEN-LAST:event_Poke2ActionPerformed

    private void Poke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke1ActionPerformed
      Charmeleon();
    }//GEN-LAST:event_Poke1ActionPerformed

    private void PokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PokemonActionPerformed
         Object source = evt.getSource();		
             if(source == Pokemon){
             if(clicks%2 == 0){
           	Poke1.setVisible(true);
           	Poke2.setVisible(true);
           	Poke3.setVisible(true);
           	Poke4.setVisible(true);
                Poke5.setVisible(true);
           	Poke6.setVisible(true);
             }
             if(clicks%2 == 1){
           	  Poke1.setVisible(false);
           	Poke2.setVisible(false);
           	Poke3.setVisible(false);
           	Poke4.setVisible(false);
                Poke5.setVisible(false);
           	Poke6.setVisible(false);
             }     
              clicks++;  
           }           
    }//GEN-LAST:event_PokemonActionPerformed

    private void Poke3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke3ActionPerformed
        Butterfree();
    }//GEN-LAST:event_Poke3ActionPerformed

    private void Poke4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke4ActionPerformed
       Ekans();
    }//GEN-LAST:event_Poke4ActionPerformed

    private void Poke5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke5ActionPerformed
       Pigeotto();
    }//GEN-LAST:event_Poke5ActionPerformed

    private void Poke6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poke6ActionPerformed
      Rattata();
    }//GEN-LAST:event_Poke6ActionPerformed

    private void Skill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill1ActionPerformed
        skill1();
    }//GEN-LAST:event_Skill1ActionPerformed

    private void Skill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill2ActionPerformed
      skill1();
    }//GEN-LAST:event_Skill2ActionPerformed

    private void Skill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill3ActionPerformed
      skill1();
    }//GEN-LAST:event_Skill3ActionPerformed

    private void Skill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill4ActionPerformed
      skill1();
    }//GEN-LAST:event_Skill4ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new run().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bag;
    private javax.swing.JLabel Epoke;
    private javax.swing.JButton Fight;
    private javax.swing.JLabel HP;
    private javax.swing.JLabel HP1;
    private javax.swing.JLabel Lv;
    private javax.swing.JLabel Lv1;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JButton Poke1;
    private javax.swing.JButton Poke2;
    private javax.swing.JButton Poke3;
    private javax.swing.JButton Poke4;
    private javax.swing.JButton Poke5;
    private javax.swing.JButton Poke6;
    private javax.swing.JButton Pokemon;
    private javax.swing.JButton Run;
    private javax.swing.JButton Skill1;
    private javax.swing.JButton Skill2;
    private javax.swing.JButton Skill3;
    private javax.swing.JButton Skill4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel poke;
    // End of variables declaration//GEN-END:variables
    
    public void Charmeleon(){
    icon = new ImageIcon(getClass().getResource("Charmeleon.png"));
    icon.getImage().flush();
    poke.setIcon(icon);
    Skill1.setText((String)pk.ch.get(0));
    Skill2.setText((String)pk.ch.get(1));
    Skill3.setText((String)pk.ch.get(2));
    Skill4.setText((String)pk.ch.get(3));
    pk.heal = 360;
    HP1.setText(String.valueOf(pk.heal));
    Name1.setText((String)pk.name.get(0));
    Lv1.setText((String)("Lv."+pk.lv));	
    input1 = "Charmeleon";
    random = (int)(Math.random()*10+50);
 }
    public void Ivysaur(){
     icon = new ImageIcon(getClass().getResource("Ivysaur.png"));
    icon.getImage().flush();
    poke.setIcon(icon);
    Skill1.setText((String)pk.iv.get(0));
    Skill2.setText((String)pk.iv.get(1));
    Skill3.setText((String)pk.iv.get(2));
    Skill4.setText((String)pk.iv.get(3));
    pk.heal1 = 330;
    input2 = "Ivysaur";
    HP1.setText(String.valueOf(pk.heal1));
    Name1.setText((String)pk.name.get(1));
    Lv1.setText((String)("Lv."+pk.lv));		
    Fight.setEnabled(true);	      
    random = (int)(Math.random()*10+60);
    }
    public void Butterfree(){
    icon = new ImageIcon(getClass().getResource("Butterfree.png"));
    icon.getImage().flush();
    poke.setIcon(icon);
    Skill1.setText((String)pk.bu.get(0));
    Skill2.setText((String)pk.bu.get(1));
    Skill3.setText((String)pk.bu.get(2));
    Skill4.setText((String)pk.bu.get(3));
    pk.heal2 = 350;
     input3 = "Butterfree";
    HP1.setText(String.valueOf(pk.heal2));
    Name1.setText((String)pk.name.get(2));
    Lv1.setText((String)("Lv."+pk.lv));			      
    random = (int)(Math.random()*10+40);
    }
    public void Ekans(){
     icon = new ImageIcon(getClass().getResource("Ekans.png"));
    icon.getImage().flush();
    poke.setIcon(icon);
    Skill1.setText((String)pk.Ek.get(0));
    Skill2.setText((String)pk.Ek.get(1));
    Skill3.setText((String)pk.Ek.get(2));
    Skill4.setText((String)pk.Ek.get(3));
    pk.heal3 = 370;
    input3 = "Ekans";
    HP1.setText(String.valueOf(pk.heal3));
    Name1.setText((String)pk.name.get(3));
    Lv1.setText((String)("Lv."+pk.lv));		      
    random = (int)(Math.random()*10+80);
    }
    public void Pigeotto(){
      icon = new ImageIcon(getClass().getResource("Pidgeotto.png"));
    icon.getImage().flush();
    poke.setIcon(icon);
    Skill1.setText((String)pk.pi.get(0));
    Skill2.setText((String)pk.pi.get(1));
    Skill3.setText((String)pk.pi.get(2));
    Skill4.setText((String)pk.pi.get(3));
    pk.heal4 = 360;
    input5 = "Pidgeotto";
    HP1.setText(String.valueOf(pk.heal4));
    Name1.setText((String)pk.name.get(4));
    Lv1.setText((String)("Lv."+pk.lv));		      
    random = (int)(Math.random()*10+70);
    }
    public void Rattata(){
     icon = new ImageIcon(getClass().getResource("Rattata.png"));
    icon.getImage().flush();
    poke.setIcon(icon);
    Skill1.setText((String)pk.ra.get(0));
    Skill2.setText((String)pk.ra.get(1));
    Skill3.setText((String)pk.ra.get(2));
    Skill4.setText((String)pk.ra.get(3));
    pk.heal5 = 320;
    input6 = "Rattata";
    HP1.setText(String.valueOf(pk.heal5));
    Name1.setText((String)pk.name.get(5));
    Lv1.setText((String)("Lv."+pk.lv));		      
    random = (int)(Math.random()*10+50);
    }
    public void skill1(){
    	      if(pk.name.get(0).equals(input1)){		        	 		          
    		HP.setText(String.valueOf(healE - pk.atk));
    		pk.atk += random;
    	        HP1.setText(String.valueOf(pk.heal -atk));	    	   	   
    		atk += atk;	
    		if(atk >= healE){	 
    				    pk.atk = 0;	    				    
    				    atk = 0;	    					
    		     		HP1.setText("0");	
    		         	Poke1.setEnabled(false);
    		         	JOptionPane.showMessageDialog(null,"You Change Pokemon");
    		      }
         	else if(pk.atk >= pk.heal){	    	        		
    		     		pk.atk = 0;
    		 	        atk = 0;
    		 	    	healE = 0;
    		     		HP.setText("0");	        		      	
    		     		JOptionPane.showMessageDialog(null,"You WIN");	 
    		     		Run.setVisible(true);
    		     		dispose();
             	}
    		}	    
    		if(pk.name.get(1).equals(input2)){		        	 		          
	    		HP.setText(String.valueOf(healE - pk.atk2));
	    		pk.atk2 += random;
	    	    HP1.setText(String.valueOf(pk.heal1 - atk2));	    	   	   
	    		atk2 += atk2;	
	    		if(atk2 >= healE){	 
	    				    pk.atk2 = 0;	    				    
	    				    atk2 = 0;	    					
	    		     		HP1.setText("0");			     		
	    		     	    Poke2.setEnabled(false);
	    		     	   JOptionPane.showMessageDialog(null,"You Change Pokemon");
	    		     	
	    		}
	         	else if(pk.atk2 >= pk.heal1){	    	        		
	    		     		pk.atk2 = 0;
	    		 	    	atk = 0;
	    		     		HP.setText("0");	
	    		     		healE = 0;
	    		     		JOptionPane.showMessageDialog(null,"You WIN");	 
	    		     		Run.setVisible(true);
	    		     		dispose();
	         	}
	    		}	    
    		if(pk.name.get(2).equals(input3)){		        	 		          
	    		HP.setText(String.valueOf(healE - pk.atk3));
	    		pk.atk3 += random;
	    	    HP1.setText(String.valueOf(pk.heal2 -atk3));	    	   	   
	    		atk3 += atk3;	
	    		if(atk >= healE){	 
	    				    pk.atk3 = 0;	    				    
	    				    atk3 = 0;	    					
	    		     		HP1.setText("0");		
	    		         	Poke3.setEnabled(false);
	    		         	JOptionPane.showMessageDialog(null,"You Change Pokemon");
	    		      }
	         	else if(pk.atk3 >= pk.heal2){	    	        		
	    		     		pk.atk3 = 0;
	    		 	    	atk3 = 0;
	    		     		HP.setText("0");	 
	    		     		healE = 0;
	    		     		JOptionPane.showMessageDialog(null,"You WIN");	 
	    		     		Run.setVisible(true);
	    		     		dispose();
	         	}
	    		}	    
    		if(pk.name.get(3).equals(input4)){		        	 		          
	    		HP.setText(String.valueOf(healE - pk.atk4));
	    		pk.atk4 += random;
	    	    HP1.setText(String.valueOf(pk.heal3 -atk4));	    	   	   
	    		atk4 += atk4;	
	    		if(atk4 >= healE){	 
	    				   pk.atk4 = 0;	    				    
	    				    atk4 = 0;	    					
	    		     		HP1.setText("0");		
	    		         	Poke4.setEnabled(false);
	    		         	JOptionPane.showMessageDialog(null,"You Change Pokemon");
	    		      }
	         	else if(pk.atk4 >= pk.heal3){	    	        		
	    		     		pk.atk4 = 0;
	    		 	    	atk4 = 0;
	    		     		HP.setText("0");	 
	    		     		healE = 0;
	    		     		JOptionPane.showMessageDialog(null,"You WIN");	 
	    		            	Run.setVisible(true);
	    		     		dispose();
	         	}
	    		}	    
    		if(pk.name.get(4).equals(input5)){		        	 		          
	    		HP.setText(String.valueOf(healE - pk.atk5));
	    		pk.atk5 += random;
	    	    HP1.setText(String.valueOf(pk.heal4 -atk5));	    	   	   
	    		atk5 += atk5;	
	    		if(atk5 >= healE){	 
	    				    pk.atk5 = 0;	    				    
	    				    atk5 = 0;	    					
	    		     		HP1.setText("0");	
	    		         	Poke5.setEnabled(false);
	    		         	JOptionPane.showMessageDialog(null,"You Change Pokemon");
	    		      }
	         	else if(pk.atk5 >= pk.heal4){	    	        		
	    		     		pk.atk5 = 0;
	    		 	    	atk5 = 0;
	    		 	    	healE = 0;
	    		     		HP.setText("0");	        		      	
	    		     		JOptionPane.showMessageDialog(null,"You WIN");	 
	    		     		Run.setVisible(true);
	    		     		dispose();
	         	}
	    		if(pk.name.get(5).equals(input6)){		        	 		          
		    		HP.setText(String.valueOf(healE - pk.atk6));
		    		pk.atk6 += random;
		    	    HP1.setText(String.valueOf(pk.heal5 -atk6));	    	   	   
		    		atk6 += atk6;	
		    		if(atk6 >= healE){	 
		    				    pk.atk6 = 0;	    				    
		    				    atk6 = 0;	    					
		    		     		HP1.setText("0");	
		    		         	Poke6.setEnabled(false);
		    		         	JOptionPane.showMessageDialog(null,"You Change Pokemon");
		    		      }
		         	else if(pk.atk6 >= pk.heal5){	    	        		
		    		     		pk.atk = 0;
		    		 	    	atk6 = 0;
		    		 	    	healE = 0;
		    		     		HP.setText("0");	        		      	
		    		     		JOptionPane.showMessageDialog(null,"You WIN");	 
		    		     		Run.setVisible(true);
		    		     		dispose();
		         	}		    		     		
		    		}	
    		}
    }
}
